CREATE DATABASE doingsdone
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(64) NOT NULL,
	password CHAR(255) NOT NULL,
	email CHAR(128) NOT NULL UNIQUE,
	dt_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(64) NOT NULL,
	user_id INT NOT NULL
);

CREATE TABLE tasks (
	id INT AUTO_INCREMENT PRIMARY KEY,
	projec_id INT NOT NULL,
	status TINYINT NOT NULL,
	dt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	task_name CHAR(255) NOT NULL,
	file_link CHAR,
	dt_deadline DATE,
	user_id INT NOT NULL
);

CREATE FULLTEXT INDEX task_name_search ON tasks(task_name);